Разметка
htmlacademy-htmlcss/1759625-gllacy-31 pull request #2
Opened 2021-05-23 08:12 UTC by Sergey-Yudin-1981

Разметка главной страницы и страницы каталога товаров. Создание и разметка тупиковой страницы blank.html

2021-05-23 16:49 UTC, andreysgra requested changes
Не увидел в разметке этого блока:

![image](https://user-images.githubusercontent.com/17790771/119269176-0e8b5900-bbff-11eb-8069-4f436715d964.png)

---

Страницу каталога не проверял. Давайте сначала устраним ошибки на главной странице, так как часть из них пересекается со страницей каталога.

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +       <p><a href="https://htmlacademy.ru/"><img src="" width="107.89" height="30.99" alt=""></a></p>
Значением атрибутов `width` и `heigth` должны быть только целые числа. Дробные нужно округлять:
```suggestion
       <p><a href="https://htmlacademy.ru/"><img src="" width="108" height="31" alt=""></a></p>
```

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +            <li><a><img src="" width="154" height="64" alt=""></a></li> <!--логотип магазина-->
Пункт ТЗ https://up.htmlacademy.ru/htmlcss/31/project/gllacy#gllacy-3-2 - логотип не является пунктом меню. Вынесем его за пределы списка меню, но оставим в `nav`, так как это часть навигации по сайту:
```
<nav>
       <a><img src="" width="154" height="64" alt=""></a> <!--логотип магазина-->
       <ul>
            <li><a href="catalog.html">Каталог</a></li>
            <li><a href="blank.html">Доставка и оплата</a></li>
            <li><a href="blank.html">О компании</a></li>
         </ul>
         
  <! ... >
</nav>
```

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +           <button type="button">Хочу варенье!</button>
Это ссылка.

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +           <button type="button">Хочу шоколадки!</button>
Это ссылка.

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +         <input type="submit" value="ОТПРАВИТЬ">
Это элементы формы:
![image](https://user-images.githubusercontent.com/17790771/119269227-40042480-bbff-11eb-9eae-6a0b19c61b99.png)

Использование `input` без формы, считается ошибкой (критерий Б4).

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +         <input type="submit" value="ОТПРАВИТЬ">
`input type="submit"` сейчас как правило не используют. Лучше заменить на `button type="submit"

2021-05-23 16:49 UTC, andreysgra commented on index.html
> +        <button type="button">Форма обратной связи</button>
Ссылка.

2021-05-24 05:21 UTC, Sergey-Yudin-1981 commented
Внес изменения

2021-05-24 05:21 UTC, closed without merging